// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "The Planet 60",
  domain: "theplanet60.com",
  city: "Brampton",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-brampton",
  address: "1098 Peter Robertson Blvd #10, Brampton, ON L6R 1G6",
  streetAddress: "1098 Peter Robertson Blvd #10",
  postalCode: "L6R 1G6",
  phone: "(437) 230-6974",
  phoneIntl: "+14372306974",
  neighborhood: "Brampton",
  nearbyAreas: ["Brampton", "Peter Robertson Blvd", "Springdale", "Torbram Road", "Bramalea", "Brampton Transit"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.7579871",
  longitude: "-79.7371271",
  hours: ["Open 24 Hours"],
  seoTitle: "The Planet 60 | Weed Dispensary in Brampton",
  metaDescription: "The Planet 60 is a local weed dispensary in Brampton offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Brampton", "Queen Street", "Main Street"],
  introVariant: "The Planet 60 is a local weed dispensary in Brampton, located at 1098 Peter Robertson Blvd #10. We serve adults 19+ looking for quality weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories. Whether you are searching for a weed dispensary near Brampton, a cannabis store in Brampton, or a local weed shop close to Queen Street, our friendly team is here to help you find the right product.",
  neighborhoodDescription: "Located in the vibrant Brampton district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Ample free parking is available in the retail plaza lot",
  transitNote: "Served by Brampton Transit routes along Torbram Road and Peter Robertson Boulevard.",
  sectionTitle: "Serving Customers Near Peter Robertson Blvd"
};
